### PR TITLE
Using SACC as input format

### LINKED ISSUE #11: Data format
It would be good if mflike could use the SACC data format for reading (and potentially writing) power spectrum data.

Information about SACC can be found here: https://github.com/simonsobs/sacc
Some more reasons for it on these [slides](https://docs.google.com/presentation/d/1wRvcpdYH7iqgLdrTZLgsYsX6egEn9WHwj3PKDqc3EvQ/edit?usp=sharing)

### PR DESCRIPTION
**Pull request by damonge**
This PR will try to:

- [x] Implement SACC as the standard I/O format for power spectra and covariances
- [x] Update https://github.com/simonsobs/LAT_MFLike_data accordingly
- [x] Implement a more general framework to determine which power spectrum combinations and scale cuts you'd like to use.
- [x] Include in the above the possibility of summarizing TE' = (TE + ET)/2 etc.
- [x] Theory C_ells should be sampled at the window function ell-values.

Closes #11

### CODE REVIEW

**Comment by damonge** [comment]
While implementing this, I've found the following issues that could be improved:

- The treatment of bandpasses is a bit lacking (e.g. delta-bandpasses are assumed, and the different cross-spectra are identified by the numerical value of this frequency in the foreground model).
- The foreground model could be more efficient: fgspectra is imported every time the likelihood gets evaluated, and all the different foreground spectra are calculated, regardless of which of them you actually want to include.

**Comment by damonge** [comment]
OK, @xgarrido @thibautlouis this is basically ready, but before tests pass etc, we need to sort out the data.

Before that, here's a list of nags on my end:
* I find some of the structure difficult to understand. This may be due to my inexperience with cobaya. Mostly, I'm very confused about what `path`, `path_install` and `data_folder` are supposed to be. Also, not sure why we should always assume that the data will always be automatically downloaded from some github repo (if that's what's happening).
* If the unit test data has a significant size (which is the case for now), we should store them somewhere that isn't github. Alternatively, we should create easier, more lightweight tests (I'd vote for the second one).
* Better documentation would be great (this is just a general comment, I'm as much to blame here as anyone else, it's just that I had to struggle a bit to understand what was going on at first).
* Do we want to support the TE-only structure? (i.e. TE'=(TE+ET)/2)? To me it creates a lot of complexity for no good reason, but I may be missing something.
* This is missing bandpasses. I've already opened an issue for it.
* All foreground contributions are being computed by default (even if you decide you don't need some of them). This could be made more efficient. Haven't opened an issue for this, but it should be addressed somewhere else.

**Comment by thibautlouis** [comment]
1) Can we have both options enable (cobaya download (great for data release) or manual download)?
2) I agree that we don't need heavy unit tests, and with option 2.
4) TE=(TE+ET)/2 is what Planck legacy does, that's why we were thinking about considering it.

3), 5), 6) yep we are aware of that the code is still in dev.

**Comment by xgarrido** [comment]
> (1) Xavier, can we have both options enable (cobaya download (great for data release) and manual download)?

Yes. Basically, the likelihood looks into the `path` variable defines into the `yaml` file. Either you use `cobaya-install` or you download them by yourself and set the `path` into your `yaml` file accordingly. This is explained in the README file 

> Preliminary simulated data can be found in the LAT_MFLike_data repository. You can download them by yourself but you can also use the cobaya-install binary and let it do the installation job.

**Pull request merged**
