### PR TITLE
Fix numpy API deprecations np.trapz -> np.trapezoid

### PR DESCRIPTION
**Pull request by xgarrido**

### CODE REVIEW

**Comment by xgarrido** [comment]
This fails for python 3.9 and numpy < 2.0. So the fix is maybe a bit early. Can imagine to have this
```python
if np.__version__ >= "2.0.0":
  from numpy import trapezoid as trapz
else:
  from numpy import trapz
```

**Comment by sgiardie** [comment]
> This fails for python 3.9 and numpy < 2.0. So the fix is maybe a bit early. Can imagine to have this
> 
> ```python
> if np.__version__ >= "2.0.0":
>   from numpy import trapezoid as trapz
> else:
>   from numpy import trapz
> ```

Hi @xgarrido, I was also about to write that it is too early for this substitution. For example, I have issues with numpy >= 2.0 since some packages like tensorflow (required by cosmopower) require numpy < 2.
I implemented your suggestion!

**Comment by xgarrido** [comment]
You need to change the call `np.trapz` to only `trapz`

**Comment by cmbant** [comment]
Should have been merged with #90

**Pull request closed without merging**
